apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: validator-mcp-server
  namespace: validator-mcp-server
  labels:
    app.kubernetes.io/name: validator-mcp-server
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        requestPath: /health
        port: 3001
  targetRef:
    group: ""
    kind: Service
    name: validator-mcp-server
