apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backendpolicy.yaml
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - healthcheckpolicy.yaml